### ISSUE TITLE
Redwood does not run python scripts on Mac Client

### ISSUE THREAD

**Issue by yodaqua** [dmolchanenko/RedwoodHQ#10]
Hi Dmitri

I logged this [issue]([https://groups.google.com/forum/#!searchin/primatest-automation/python%7Csort:relevance/primatest-automation/jUBKXt6gQwg/dFKVv-I7EAAJ]) on the PrimaTest Google Group.

I tried the following script:
class PythonAction:
    def run(self,params):
        print ("I am Python Action")
        pass

I went through normal script -> action -> test case -> execution process. During the execution, the test step associated with the action remains in state of 'not_run'.

A runtime folder .../RedwoodHQAgent/agent/executionfiles/1471508853670-3338-10981/does appear. The Lib directory in this runtime folder does contain two zipped python folders: 'pythonLibs.zip' and 'pythonSources.zip'. The folders contain all the python modules and scripts required to run the test.

Unfortunately this does not happen. The test step is perpetually caught in a state of 'not_run'. 

I've looked at the logs. I'm not sure if this is the cause of the issue:
{"level":"error","message":"sendFileToAgent problem with request: socket hang up file:C:\\Program Files\\RedwoodHQ/logs/jar_1471508853670-3338-10981/pythonSources.zip","timestamp":"2016-09-09T08:22:20.028Z"}
{"level":"error","message":"matchFileWithAgent problem with request: Unable to read file:C:\\Program Files\\RedwoodHQ/logs/jar_1471508853670-3338-10981/pythonSources.zip ","timestamp":"2016-09-09T08:24:50.105Z"}

[server and agent logs.zip](https://github.com/dmolchanenko/RedwoodHQ/files/480507/server.and.agent.logs.zip)

Environment:
Server: 
- Windows 2012 R2 (VM in a virtual box on the client machine)
- RedwoodHQ: Version = 2.40.20
- Python 2.7.12
Client:
- Mac: OSX 10.11.3
- RedwoodHQAgent version = 2.40.20

When starting the RedwoodHQ Agent on my machine, I get the following output:
info: Agent Started.
info: getExecutionStatus result: Error: invalid json
    at Object.exports.error (C:\Program Files\RedwoodHQ\node_modules\express\node_modules\connect\lib\utils.js:44:13)
    at IncomingMessage.<anonymous> (C:\Program Files\RedwoodHQ\node_modules\express\node_modules\connect\lib\middleware\json.js:68:73)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)
info:  execution=null

Please help.

**Comment by yodaqua** [comment]
[agent_errors.log.zip](https://github.com/dmolchanenko/RedwoodHQ/files/480619/agent_errors.log.zip)
[agent.log.zip](https://github.com/dmolchanenko/RedwoodHQ/files/480620/agent.log.zip)
