### ISSUE TITLE
How to run RedwoodHQ from source code?

### ISSUE THREAD

**Issue by damien122** [dmolchanenko/RedwoodHQ#15]
Hi,
I got a strange error when I try to start RedwoodHQ from the latest source code.
When I run ``` node ./app.js ``` then I got an strange error.

``` 
error in store.js at line 35

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (c:\GIT\RedwoodHQ\node_modules\socket.io\lib\store.js:35:41)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\GIT\RedwoodHQ\node_modules\socket.io\lib\manager.js:16:13)
    at Module._compile (module.js:569:30)
``` 

I have installed node.js version 8.0 (last release) and execute ``` nmp install```  previous.

Unfortunatelly I also can't find any further information how to run the framework from source code. 
Also I can't find a requirement list for a dev environment.

Could you please help me?

Regards
Damien

**Comment by damien122** [comment]
After installing MongoDB on my PC I got an other strange output

````
js-bson: Failed to load c++ bson extension, using pure JS version
get db reference
========================================================================================
=  Please ensure that you set the default write concern for the database by setting    =
=   one of the options                                                                 =
=                                                                                      =
=     w: (value of > -1 or the string 'majority'), where < 1 means                     =
=        no write acknowledgement                                                       =
=     journal: true/false, wait for flush to journal before acknowledgement             =
=     fsync: true/false, wait for flush to file system before acknowledgement           =
=                                                                                      =
=  For backward compatibility safe is still supported and                              =
=   allows values of [true | false | {j:true} | {w:n, wtimeout:n} | {fsync:true}]      =
=   the default value is false which means the driver receives does not                =
=   return the information of the success/error of the insert/update/remove            =
=                                                                                      =
=   ex: new Db(new Server('localhost', 27017), {safe:false})                           =
=                                                                                      =
=   http://www.mongodb.org/display/DOCS/getLastError+Command                           =
=                                                                                      =
=  The default of no acknowledgement will change in the very near future                =
=                                                                                      =
=  This message will disappear when the default safe is set on the driver Db           =
========================================================================================

````

**Comment by damien122** [comment]
anybody??

**Comment by wolterskluwer-redwoodhq** [comment]
Download and install the software then overlay the git repo source on top of the installed software. Its the best way to ensure you have all the dependencies installed.

As well, this question is better asked in the Google forum for RedwoodHQ: [https://groups.google.com/forum/#!forum/primatest-automation](url)

**Comment by damien122** [comment]
@wolterskluwer-redwoodhq 
Ok thanks I will try.
Did you still use Redwood at your company?

**Comment by wolterskluwer-redwoodhq** [comment]
@damien122 yes we do. It is the platform all the teams use to develop and run test (and other) automation.

**Comment by damien122** [comment]
@wolterskluwer-redwoodhq 
verwendet ihr Redwood auch für VM steuerung? oder habt ihr feste Maschinen die nie abgeschaltet werden?

**Comment by wolterskluwer-redwoodhq** [comment]
We run agents inside docker containers. The whole thing is orchestrated via our CI system.

**Comment by mohitrathi92** [comment]
@damien122 - Were you able to run the source code? If so how? and can you please help with this regard?

**Comment by damien122** [comment]
@mohitrathi92 sorry I can't remember. It is a long time ago.

**Comment by mohitrathi92** [comment]
Oki no problem, thanks for your response :)
